services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "SqlServer2019"
      MSSQL_PID: "Developer"
    ports:
    - "1433:1433"